"""
Description: Worker 启动入口
Generated by: Talos
"""

from __future__ import annotations

import asyncio
import os

from loguru import logger

from core.config.config_center import get_app_config, get_worker_config
from core.logging import setup_logger
from core.task.worker import load_task_modules
from core.task.worker_manager import WorkerManager, setup_signal_handlers


def create_worker_manager() -> WorkerManager:
    """从配置创建 WorkerManager 实例."""
    app_config = get_app_config()
    worker_config = get_worker_config()
    return WorkerManager(
        queue_name=worker_config.queue_name,
        max_jobs=worker_config.max_jobs,
        job_timeout=worker_config.job_timeout,
        keep_result=worker_config.keep_result,
        health_check_interval=worker_config.health_check_interval,
        retry_jobs=worker_config.retry_jobs,
        max_tries=worker_config.max_tries,
        redis_mode=app_config.redis_mode,
        redis_host=app_config.redis_host,
        redis_port=app_config.redis_port,
        redis_db=app_config.redis_db,
        redis_password=app_config.redis_password,
        redis_max_connections=app_config.redis_max_connections,
        redis_cluster_nodes=app_config.redis_cluster_nodes,
        mongo_db_name=app_config.mongo_db_name,
    )


async def main() -> None:
    worker_log_suffix = os.getenv("WORKER_LOG_SUFFIX", "worker").strip() or "worker"
    setup_logger(file_suffix=worker_log_suffix)

    # 惰性加载 task 注册模块
    config = get_app_config()
    if config.task_modules:
        load_task_modules(config.task_modules)

    worker_manager = create_worker_manager()
    setup_signal_handlers(worker_manager)

    started = await worker_manager.start_worker()
    if not started:
        logger.error("Worker failed to start")
        return

    if worker_manager.worker_task:
        try:
            await worker_manager.worker_task
        except asyncio.CancelledError:
            logger.info("Worker task cancelled")


if __name__ == "__main__":
    asyncio.run(main())
